[project]
name = "fastapi-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.128.0",
    "psycopg[binary]>=3.3.2",
    "sqlalchemy>=2.0.45",
    "uvicorn[standard]>=0.40.0",
]
